### ISSUE TITLE
[Bug]: compile failed on linux when following the readme

### ISSUE THREAD

**Issue by zhiqiangxu** [dominant-strategies/quai-gpu-miner#16]
### Bug Description

When I follow the [readme](https://github.com/dominant-strategies/quai-gpu-miner?tab=readme-ov-file#ubuntu--osx) and run `cmake .. -DETHASHCUDA=ON -DETHASHCL=ON -DAPICORE=ON`, there're compile errors, the first error is:

<img width="992" alt="image" src="https://github.com/user-attachments/assets/dd8458ba-5276-4929-bb69-dfa15a9fba60">

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/a338dfb6-de8d-4126-a81a-3c87879f061f">

### Version

latest version, commit 74368bdd5665a5d6a5d0360c032622afa59a6605

### Environment

Linux xxx 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior

It should compile successfully when following the readme.

### Actual Behavior

`cmake .. -DETHASHCUDA=ON -DETHASHCL=ON -DAPICORE=ON` failed with the snapshot error.

### Relevant Code or Logs

There's no code change.

**Comment by Djadih** [comment]
Triage via ticket, if valid we will reopen
